#!/usr/bin/env python
import rospy
from rsync_ros.rsync_service_node import RsyncServiceServer

if __name__ == '__main__':
    rospy.init_node('RsyncServer')
    rsync_provider = RsyncServiceServer()
    rsync_provider.spin()
